name: Scraping SINADEF

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    if: "contains(github.event.head_commit.message, 'initial commit')"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install package dependencies
        run: Rscript -e "install.packages(c('tidyverse', 'vroom'))"
      - name: Download and save data
        run: Rscript -e "source('script/00_get_data.R')"
      - name: Commit results
        run: |
          today=$(date +"%Y-%m-%d")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "updated datasets ${today}"
          git push origin master
